# Generated by Django 5.1.7 on 2025-03-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('predicted_boxes', models.JSONField(default=list)),
                ('corrected_boxes', models.JSONField(blank=True, default=list, null=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
    ]
